### ISSUE TITLE
Mostrar ultimas votaciones

### ISSUE THREAD

**Issue by sanframar** [Trabajo-EGC/Censo#1]
Para mostrar más información acerca de las últimas votaciones que se han realizado en nuestro sistema sería conveniente que se mostrasen en una ventana nueva dichas votaciones.
Esta información debería de salir en la ventana principal de nuestra aplicación.

**Comment by simegegue** [comment]
Encontrado un error que provoca que se muestren los fechas de inicio como las fechas de fin de votación y viceversa.
