### ISSUE TITLE
Buscador de censos por titulo

### ISSUE THREAD

**Issue by sanframar** [Trabajo-EGC/Censo#19]
Se debe de implementar una nueva funcionalidad la cuál permitirá buscar los censos que coincidan con la palabra clave.

**Comment by sanframar** [comment]
Se ha implementado correctamente esta funcionalidad y se han realizado las pruebas pertinentes para comprobar su correcto funcionamiento.

**Comment by rubbarmoh** [comment]
Existen problemas con el buscador por título. Se reabre para darle solución.

**Comment by rubbarmoh** [comment]
Se corrigen los problemas con el buscador y las funcionalidades.
