### ISSUE TITLE
Creación de tests

### ISSUE THREAD

**Issue by sanframar** [Trabajo-EGC/Censo#22]
Hay varias funciones que carecen de un test para comprobar su correcto funcionamiento por lo que dichos tests se deben de realizar dentro de la carpeta correspondiente "test/java/services/CensusServiceTest.java".

**Comment by pabromvaz** [comment]
Test del buscador por titulo creado

**Comment by pabromvaz** [comment]
Test most popular creado y corregidos los comentarios de los test
