### ISSUE TITLE
Mejora de la documentación

### ISSUE THREAD

**Issue by sanframar** [Trabajo-EGC/Censo#23]
Se debe de mejorar la documentación ya que es demasiado pobre. Para ello se deberá de seguir el esquema que el profesor nos ha facilitado. https://1984.lsi.us.es/wiki-egc/index.php/Comentarios_para_mejorar_los_trabajos_16-17

**Comment by rubbarmoh** [comment]
Se ha incluido en la documentación el proceso de despliegue, y el estudio de los posibles hostings.
