### ISSUE TITLE
Despliegue de apliación

### ISSUE THREAD

**Issue by rubbarmoh** [Trabajo-EGC/Censo#25]

**Comment by simegegue** [comment]
Se ha configurado una maquina virtual como servidor y en esta maquina se ha realizado el despliegue de nuestro modulo. En esta maquina también se ha instalado jenkins para hacer el despliegue automático. Falta realizar pruebas para comprobar que se realiza el despliegue correctamente.

**Comment by rubbarmoh** [comment]
Se ha completado la automatización del despliegue de forma satisfactoria.
