### ISSUE TITLE
Modificación de las fechas de los censos

### ISSUE THREAD

**Issue by sanframar** [Trabajo-EGC/Censo#7]
Se deben de modificar las fechas tanto de apertura como de cierre de los censos ya que a la hora de realizar pruebas con la base de datos la inmensa mayoría de los censos ya han cerrado.
Sería conveniente que se modificase estos datos antes de almacenarlos en la base de datos y no después ya que podría causar problemas.

**Comment by simegegue** [comment]
He añadido varios censos para poder realizar pruebas. He creado censos con fechas de fin recientes y con fechas de finalización futuras.
